public class FindtheDifference {
    public static void main(String[] args) {
        System.out.println(FindtheDifference.findTheDifference("abcd","abcde"));
    }

    private static char findTheDifference(String s, String t) {

        return (char) (findStringSum(t) - findStringSum(s));
    }

    private static int findStringSum(String s) {
        int sum = 0;
        for(int i=0;i<s.length();i++)
            sum += (int) s.charAt(i);
        return sum;
    }


}

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 */